export { analyzeStudentSimulado } from './simulado/analyze'
export { diagnoseStudentAnswers } from './simulado/diagnostics'
export { getLatestSimuladoResult } from './simulado/latest-result'
export { getSimuladoFromProjetos } from './simulado/projetos'
export { getRealStudentErrors } from './simulado/real-errors'
export { getStudentByMatricula } from './simulado/student'
export { getTRIScoresFromStudentAnswers } from './simulado/tri-scores'
