version: '3.8'

services:
  xtri-cronogramas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xtri-cronogramas
    restart: always
    ports:
      - "3000:80"
    networks:
      - xtri-network

networks:
  xtri-network:
    driver: bridge
