/**
 * Tradução de habilidades ENEM (identificador oficial) para
 * linguagem didática que o aluno entende.
 *
 * Fonte: enem_habilidades (Supabase qgqliquusdkkwnfuzdwi)
 * Total: 120 habilidades (30 por área)
 */

/** Tradução de habilidades ENEM para linguagem do aluno */
export const HABILIDADE_CONTEUDO: Readonly<Record<string, string>> = {
  // ── Ciências Humanas (CH) ──────────────────────────────
  'CH-H1': 'Cultura e Fontes Históricas',
  'CH-H2': 'Memória e Sociedade',
  'CH-H3': 'Cultura Atual e Processos Históricos',
  'CH-H4': 'Pontos de Vista sobre Cultura',
  'CH-H5': 'Patrimônio Cultural e Diversidade',
  'CH-H6': 'Mapas e Representações Geográficas',
  'CH-H7': 'Relações de Poder entre Nações',
  'CH-H8': 'Estado, Migração e Economia',
  'CH-H9': 'Organizações Políticas e Sociais',
  'CH-H10': 'Movimentos Sociais e Participação',
  'CH-H11': 'Práticas Sociais no Tempo e Espaço',
  'CH-H12': 'Justiça e Organização Social',
  'CH-H13': 'Movimentos Sociais e Poder',
  'CH-H14': 'Textos Analíticos e Instituições',
  'CH-H15': 'Conflitos ao Longo da História',
  'CH-H16': 'Tecnologia e Trabalho',
  'CH-H17': 'Tecnologia e Território',
  'CH-H18': 'Produção de Riqueza e Espaço',
  'CH-H19': 'Espaço Rural e Urbano',
  'CH-H20': 'Tecnologia e Vida Social',
  'CH-H21': 'Mídia e Sociedade',
  'CH-H22': 'Lutas Sociais e Políticas Públicas',
  'CH-H23': 'Ética e Política',
  'CH-H24': 'Cidadania e Democracia',
  'CH-H25': 'Inclusão Social',
  'CH-H26': 'Ocupação do Espaço e Paisagem',
  'CH-H27': 'Sociedade e Meio Físico',
  'CH-H28': 'Tecnologia e Impacto Ambiental',
  'CH-H29': 'Recursos Naturais e Espaço',
  'CH-H30': 'Preservação e Degradação Ambiental',

  // ── Ciências da Natureza (CN) ──────────────────────────
  'CN-H1': 'Ondas e Fenômenos Ondulatórios',
  'CN-H2': 'Ciência, Tecnologia e Sociedade',
  'CN-H3': 'Ciência vs Senso Comum',
  'CN-H4': 'Intervenção Ambiental e Sustentável',
  'CN-H5': 'Circuitos e Eletricidade',
  'CN-H6': 'Manuais e Sistemas Tecnológicos',
  'CN-H7': 'Controle de Qualidade e Consumo',
  'CN-H8': 'Recursos Naturais e Reciclagem',
  'CN-H9': 'Ciclos Biogeoquímicos e Energia',
  'CN-H10': 'Poluição e Impactos Ambientais',
  'CN-H11': 'Biotecnologia e Ética',
  'CN-H12': 'Impactos de Atividades Econômicas',
  'CN-H13': 'Genética e Hereditariedade',
  'CN-H14': 'Fisiologia e Processos Vitais',
  'CN-H15': 'Modelos e Experimentos Biológicos',
  'CN-H16': 'Evolução e Classificação dos Seres',
  'CN-H17': 'Leitura de Gráficos em Ciências',
  'CN-H18': 'Propriedades e Tecnologia',
  'CN-H19': 'Métodos Científicos e Sociedade',
  'CN-H20': 'Movimento e Mecânica',
  'CN-H21': 'Termodinâmica e Eletromagnetismo',
  'CN-H22': 'Radiação e Matéria',
  'CN-H23': 'Energia e Transformações',
  'CN-H24': 'Nomenclatura Química',
  'CN-H25': 'Materiais e Substâncias Químicas',
  'CN-H26': 'Recursos Energéticos e Minerais',
  'CN-H27': 'Intervenção Ambiental e Química',
  'CN-H28': 'Adaptação dos Seres e Ecologia',
  'CN-H29': 'Experimentos com Seres Vivos',
  'CN-H30': 'Saúde Individual e Coletiva',

  // ── Linguagens e Códigos (LC) ──────────────────────────
  'LC-H1': 'Linguagens e Comunicação',
  'LC-H2': 'Comunicação e Problemas Sociais',
  'LC-H3': 'Informação e Função Social',
  'LC-H4': 'Crítica aos Usos da Linguagem',
  'LC-H5': 'Vocabulário em Língua Estrangeira',
  'LC-H6': 'Língua Estrangeira e Acesso',
  'LC-H7': 'Estruturas de Língua Estrangeira',
  'LC-H8': 'Diversidade Cultural em LEM',
  'LC-H9': 'Corpo e Práticas Sociais',
  'LC-H10': 'Hábitos Corporais e Saúde',
  'LC-H11': 'Linguagem Corporal e Interação',
  'LC-H12': 'Funções da Arte',
  'LC-H13': 'Arte, Cultura e Preconceitos',
  'LC-H14': 'Diversidade Artística e Étnica',
  'LC-H15': 'Literatura e Contexto Histórico',
  'LC-H16': 'Construção do Texto Literário',
  'LC-H17': 'Valores no Patrimônio Literário',
  'LC-H18': 'Estrutura e Progressão Textual',
  'LC-H19': 'Funções da Linguagem',
  'LC-H20': 'Patrimônio Linguístico Nacional',
  'LC-H21': 'Recursos Verbais e Persuasão',
  'LC-H22': 'Opinião e Recursos Linguísticos',
  'LC-H23': 'Objetivos e Público-Alvo do Texto',
  'LC-H24': 'Estratégias Argumentativas',
  'LC-H25': 'Variação Linguística',
  'LC-H26': 'Variedades Linguísticas e Uso',
  'LC-H27': 'Norma Padrão da Língua',
  'LC-H28': 'Tecnologias da Comunicação',
  'LC-H29': 'Linguagens das Tecnologias',
  'LC-H30': 'Tecnologia e Desenvolvimento',

  // ── Matemática (MT) ────────────────────────────────────
  'MT-H1': 'Números e Operações no Cotidiano',
  'MT-H2': 'Padrões Numéricos e Contagem',
  'MT-H3': 'Problemas com Números',
  'MT-H4': 'Razoabilidade de Resultados',
  'MT-H5': 'Intervenção com Números',
  'MT-H6': 'Localização no Espaço',
  'MT-H7': 'Figuras Planas e Espaciais',
  'MT-H8': 'Problemas de Geometria',
  'MT-H9': 'Geometria no Cotidiano',
  'MT-H10': 'Grandezas e Unidades de Medida',
  'MT-H11': 'Escalas e Representações',
  'MT-H12': 'Problemas com Medidas',
  'MT-H13': 'Medição e Argumentação',
  'MT-H14': 'Geometria e Grandezas Aplicadas',
  'MT-H15': 'Relação entre Grandezas',
  'MT-H16': 'Proporcionalidade',
  'MT-H17': 'Variação de Grandezas',
  'MT-H18': 'Intervenção com Grandezas',
  'MT-H19': 'Expressões Algébricas',
  'MT-H20': 'Gráficos Cartesianos',
  'MT-H21': 'Problemas de Álgebra',
  'MT-H22': 'Álgebra e Geometria Argumentativa',
  'MT-H23': 'Intervenção com Álgebra',
  'MT-H24': 'Inferência com Gráficos e Tabelas',
  'MT-H25': 'Problemas com Gráficos e Tabelas',
  'MT-H26': 'Análise de Gráficos e Tabelas',
  'MT-H27': 'Média, Mediana e Dispersão',
  'MT-H28': 'Estatística e Probabilidade',
  'MT-H29': 'Argumentação com Estatística',
  'MT-H30': 'Intervenção com Estatística',
} as const

/** Retorna o conteúdo didático ou o identificador original se não mapeado */
export function getConteudoDidatico(identificador: string): string {
  return HABILIDADE_CONTEUDO[identificador] ?? identificador
}

/** Nomes das áreas do ENEM */
export const AREA_NOME: Readonly<Record<string, string>> = {
  CH: 'Ciências Humanas',
  CN: 'Ciências da Natureza',
  LC: 'Linguagens e Códigos',
  MT: 'Matemática',
} as const
